# Generated by Django 4.2 on 2024-05-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='superuser',
            field=models.BooleanField(default=True),
        ),
    ]
