# Generated by Django 4.2 on 2024-05-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_guard_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='superuser',
        ),
    ]
