# Generated by Django 4.2 on 2024-05-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_guard_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guard',
        ),
    ]
