# Generated by Django 4.2.11 on 2024-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_security_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identity_qrcode',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
